// AUTO-GENERATED FROM WORKSPACE ROOT. DO NOT EDIT THIS FILE DIRECTLY.
// Run from root: npm run sync:common

export const LEAVE_TYPES = ["casual", "sick", "special"] as const
export type LeaveType = (typeof LEAVE_TYPES)[number]

export const LEAVE_STATUSES = ["pending", "approved", "rejected", "cancelled"] as const
export type LeaveStatus = (typeof LEAVE_STATUSES)[number]

export const LEAVE_DURATION_TYPES = ["full", "half_morning", "half_afternoon"] as const
export type LeaveDurationType = (typeof LEAVE_DURATION_TYPES)[number]

export function isValidLeaveType(value: unknown): value is LeaveType {
  return typeof value === "string" && LEAVE_TYPES.includes(value as LeaveType)
}

export function isValidDurationType(value: unknown): value is LeaveDurationType {
  return typeof value === "string" && LEAVE_DURATION_TYPES.includes(value as LeaveDurationType)
}

export function calculateLeaveDays(startDate: string, endDate: string, durationType: LeaveDurationType): number {
  const start = new Date(startDate)
  const end = new Date(endDate)

  if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) {
    throw new Error("Invalid date format")
  }

  if (end < start) {
    throw new Error("End date must be on or after start date")
  }

  const diffDays = Math.floor((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24)) + 1

  if (durationType === "full") {
    return diffDays
  }

  if (diffDays !== 1) {
    throw new Error("Half-day leave can only be requested for a single date")
  }

  return 0.5
}
