// AUTO-GENERATED FROM WORKSPACE ROOT. DO NOT EDIT THIS FILE DIRECTLY.
// Run from root: npm run sync:common

export const FORWARD_HEADERS = ["authorization", "content-type", "accept", "user-agent"]
export const INTEGRATION_SOURCE_HEADER = "x-integration-source"
export const INTEGRATION_SOURCE_VALUE = "attendance-system"

export function getLeaveflowBaseUrl(raw: string | undefined): string | null {
  const base = raw?.trim()
  if (!base) return null
  return base.replace(/\/$/, "")
}

export function buildLeaveflowTargetUrl(base: string, path: string[] | undefined, search: string): string {
  const suffix = (path || []).join("/")
  const routePath = suffix ? `/${suffix}` : ""
  return `${base}${routePath}${search || ""}`
}

export function pickForwardHeaders(getHeader: (name: string) => string | null): Record<string, string> {
  const output: Record<string, string> = {}

  for (const key of FORWARD_HEADERS) {
    const value = getHeader(key)
    if (value) {
      output[key] = value
    }
  }

  output[INTEGRATION_SOURCE_HEADER] = INTEGRATION_SOURCE_VALUE
  return output
}
