-- Timetable Scheduling Application Database Schema
-- Comprehensive schema for faculty, subjects, classrooms, sections, and timetable generation

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Departments table
CREATE TABLE IF NOT EXISTS departments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(100) NOT NULL UNIQUE,
  code VARCHAR(20) NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Faculty table
CREATE TABLE IF NOT EXISTS faculty (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE,
  department_id UUID REFERENCES departments(id) ON DELETE SET NULL,
  phone VARCHAR(20),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Faculty availability table (stores available time slots)
CREATE TABLE IF NOT EXISTS faculty_availability (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  faculty_id UUID NOT NULL REFERENCES faculty(id) ON DELETE CASCADE,
  day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 6), -- 0=Monday, 6=Sunday
  start_period INTEGER NOT NULL CHECK (start_period BETWEEN 1 AND 8), -- Period 1-8
  end_period INTEGER NOT NULL CHECK (end_period BETWEEN 1 AND 8),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(faculty_id, day_of_week, start_period, end_period)
);

-- Subjects table
CREATE TABLE IF NOT EXISTS subjects (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(100) NOT NULL,
  code VARCHAR(20) NOT NULL UNIQUE,
  subject_type VARCHAR(20) NOT NULL CHECK (subject_type IN ('theory', 'lab')),
  periods_per_week INTEGER NOT NULL CHECK (periods_per_week > 0),
  department_id UUID REFERENCES departments(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Subject-Faculty mapping
CREATE TABLE IF NOT EXISTS subject_faculty (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  subject_id UUID NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  faculty_id UUID NOT NULL REFERENCES faculty(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(subject_id, faculty_id)
);

-- Classrooms table
CREATE TABLE IF NOT EXISTS classrooms (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(50) NOT NULL UNIQUE,
  capacity INTEGER NOT NULL CHECK (capacity > 0),
  room_type VARCHAR(20) NOT NULL CHECK (room_type IN ('lab', 'theory')),
  building VARCHAR(50),
  floor INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Academic years table
CREATE TABLE IF NOT EXISTS academic_years (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  year_level INTEGER NOT NULL CHECK (year_level BETWEEN 1 AND 4), -- 1=First year, 4=Fourth year
  name VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Sections table
CREATE TABLE IF NOT EXISTS sections (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(50) NOT NULL UNIQUE,
  year_level INTEGER NOT NULL CHECK (year_level BETWEEN 1 AND 4),
  student_count INTEGER NOT NULL CHECK (student_count > 0),
  department_id UUID REFERENCES departments(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Section-Subject mapping (which subjects a section takes)
CREATE TABLE IF NOT EXISTS section_subjects (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  section_id UUID NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
  subject_id UUID NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  faculty_id UUID NOT NULL REFERENCES faculty(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(section_id, subject_id)
);

-- Timetable generation jobs
CREATE TABLE IF NOT EXISTS timetable_jobs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'generating_base', 'base_complete', 'optimizing', 'completed', 'failed')),
  progress INTEGER DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
  message TEXT,
  base_generation_time INTEGER, -- milliseconds
  optimization_time INTEGER, -- milliseconds
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Base timetable (generated by ILP)
CREATE TABLE IF NOT EXISTS timetable_base (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  job_id UUID NOT NULL REFERENCES timetable_jobs(id) ON DELETE CASCADE,
  section_id UUID NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
  subject_id UUID NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  faculty_id UUID NOT NULL REFERENCES faculty(id) ON DELETE CASCADE,
  classroom_id UUID NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
  day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 5), -- 0=Monday, 5=Saturday
  start_period INTEGER NOT NULL CHECK (start_period BETWEEN 1 AND 8),
  end_period INTEGER NOT NULL CHECK (end_period BETWEEN 1 AND 8),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Optimized timetable (optimized by GA)
CREATE TABLE IF NOT EXISTS timetable_optimized (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  job_id UUID NOT NULL REFERENCES timetable_jobs(id) ON DELETE CASCADE,
  section_id UUID NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
  subject_id UUID NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  faculty_id UUID NOT NULL REFERENCES faculty(id) ON DELETE CASCADE,
  classroom_id UUID NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
  day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 5),
  start_period INTEGER NOT NULL CHECK (start_period BETWEEN 1 AND 8),
  end_period INTEGER NOT NULL CHECK (end_period BETWEEN 1 AND 8),
  fitness_score DECIMAL(10, 4),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_faculty_dept ON faculty(department_id);
CREATE INDEX IF NOT EXISTS idx_faculty_code ON faculty(code);
CREATE INDEX IF NOT EXISTS idx_faculty_availability_faculty ON faculty_availability(faculty_id);
CREATE INDEX IF NOT EXISTS idx_subjects_dept ON subjects(department_id);
CREATE INDEX IF NOT EXISTS idx_subject_faculty_subject ON subject_faculty(subject_id);
CREATE INDEX IF NOT EXISTS idx_subject_faculty_faculty ON subject_faculty(faculty_id);
CREATE INDEX IF NOT EXISTS idx_sections_dept ON sections(department_id);
CREATE INDEX IF NOT EXISTS idx_section_subjects_section ON section_subjects(section_id);
CREATE INDEX IF NOT EXISTS idx_section_subjects_subject ON section_subjects(subject_id);
CREATE INDEX IF NOT EXISTS idx_timetable_base_job ON timetable_base(job_id);
CREATE INDEX IF NOT EXISTS idx_timetable_base_section ON timetable_base(section_id);
CREATE INDEX IF NOT EXISTS idx_timetable_base_faculty ON timetable_base(faculty_id);
CREATE INDEX IF NOT EXISTS idx_timetable_optimized_job ON timetable_optimized(job_id);
CREATE INDEX IF NOT EXISTS idx_timetable_optimized_section ON timetable_optimized(section_id);

-- Row Level Security (RLS) - Enable for all tables
ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE faculty ENABLE ROW LEVEL SECURITY;
ALTER TABLE faculty_availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE subject_faculty ENABLE ROW LEVEL SECURITY;
ALTER TABLE classrooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE academic_years ENABLE ROW LEVEL SECURITY;
ALTER TABLE sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE section_subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE timetable_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE timetable_base ENABLE ROW LEVEL SECURITY;
ALTER TABLE timetable_optimized ENABLE ROW LEVEL SECURITY;

-- RLS Policies (Allow all operations for authenticated users - adjust based on your auth requirements)
-- Departments
CREATE POLICY "Allow all operations on departments" ON departments FOR ALL USING (true) WITH CHECK (true);

-- Faculty
CREATE POLICY "Allow all operations on faculty" ON faculty FOR ALL USING (true) WITH CHECK (true);

-- Faculty Availability
CREATE POLICY "Allow all operations on faculty_availability" ON faculty_availability FOR ALL USING (true) WITH CHECK (true);

-- Subjects
CREATE POLICY "Allow all operations on subjects" ON subjects FOR ALL USING (true) WITH CHECK (true);

-- Subject Faculty
CREATE POLICY "Allow all operations on subject_faculty" ON subject_faculty FOR ALL USING (true) WITH CHECK (true);

-- Classrooms
CREATE POLICY "Allow all operations on classrooms" ON classrooms FOR ALL USING (true) WITH CHECK (true);

-- Academic Years
CREATE POLICY "Allow all operations on academic_years" ON academic_years FOR ALL USING (true) WITH CHECK (true);

-- Sections
CREATE POLICY "Allow all operations on sections" ON sections FOR ALL USING (true) WITH CHECK (true);

-- Section Subjects
CREATE POLICY "Allow all operations on section_subjects" ON section_subjects FOR ALL USING (true) WITH CHECK (true);

-- Timetable Jobs
CREATE POLICY "Allow all operations on timetable_jobs" ON timetable_jobs FOR ALL USING (true) WITH CHECK (true);

-- Timetable Base
CREATE POLICY "Allow all operations on timetable_base" ON timetable_base FOR ALL USING (true) WITH CHECK (true);

-- Timetable Optimized
CREATE POLICY "Allow all operations on timetable_optimized" ON timetable_optimized FOR ALL USING (true) WITH CHECK (true);
